specVersion: 0.0.1
description: Substrate slots auction data collector
repository: git@github.com:subvis-io/subquery-spectator.git
schema: ./schema.graphql
network:
  endpoint: wss://polkadot.api.onfinality.io/public-ws
  # endpoint: wss://kusama-rpc.polkadot.io/
  # endpoint: wss://rococo-rpc.polkadot.io/
  # endpoint: wss://rococo.aresprotocol.com
  # endpoint: wss://node-6793473089227190272.jm.onfinality.io/ws?apikey=2c3f93ff-c795-47ce-8c63-9ede23ba6a66

  # Optionally provide the HTTP endpoint of a full chain dictionary to speed up processing
  dictionary: "https://api.subquery.network/sq/subquery/dictionary-polkadot"

definitions:
  mapping: &fnmapping
    handlers:
      - handler: handleBlock
        kind: substrate/BlockHandler
      - handler: handleEvent
        kind: substrate/EventHandler

dataSources:
  - name: rococoRuntime
    kind: substrate/Runtime
    filter:
      specName: rococo
    startBlock: 357245
    mapping: *fnmapping

  - name: kusamaRuntime
    kind: substrate/Runtime
    filter:
      specName: kusama
    startBlock: 7828000 #8231811 #7828000
    mapping: *fnmapping

  - name: polkadotRuntime
    kind: substrate/Runtime
    filter:
      specName: polkadot
    startBlock: 7353300
    mapping: *fnmapping
